// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFstLnSyZUTrLIsvx2byq5j8UULmOxsaI',
    appId: '1:1022823009147:web:d02d9348c83a8658e34bde',
    messagingSenderId: '1022823009147',
    projectId: 'enviz-fb248',
    authDomain: 'enviz-fb248.firebaseapp.com',
    storageBucket: 'enviz-fb248.appspot.com',
    measurementId: 'G-C03QYPYP62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhSfaI5N_zNyuZ8eu4M9Zw30Gz0o_D-Fs',
    appId: '1:1022823009147:android:07ef7e1d4d9c2449e34bde',
    messagingSenderId: '1022823009147',
    projectId: 'enviz-fb248',
    storageBucket: 'enviz-fb248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpFeqEJFKKhxDS6n4bJziU4L2fVUNi-04',
    appId: '1:1022823009147:ios:77f0de81292db5d7e34bde',
    messagingSenderId: '1022823009147',
    projectId: 'enviz-fb248',
    storageBucket: 'enviz-fb248.appspot.com',
    iosBundleId: 'com.example.highchartsDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFstLnSyZUTrLIsvx2byq5j8UULmOxsaI',
    appId: '1:1022823009147:web:1a6b2caf67bac19ae34bde',
    messagingSenderId: '1022823009147',
    projectId: 'enviz-fb248',
    authDomain: 'enviz-fb248.firebaseapp.com',
    storageBucket: 'enviz-fb248.appspot.com',
    measurementId: 'G-ZNJQXPJBQ1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpFeqEJFKKhxDS6n4bJziU4L2fVUNi-04',
    appId: '1:1022823009147:ios:7aeee72ab80e3264e34bde',
    messagingSenderId: '1022823009147',
    projectId: 'enviz-fb248',
    storageBucket: 'enviz-fb248.appspot.com',
    iosBundleId: 'yes',
  );

}